spring:
  datasource:
    url: jdbc:postgresql://test-db.cke9i7be2zas.us-east-1.rds.amazonaws.com:5432/test-db
    username: postgres
    password: +123456789qw
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update