spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test-db
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update