name: Java CI/CD with Gradle

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build bootJar
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: app-artifact
          path: ./build/libs/

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Download app artifact
        uses: actions/download-artifact@v2
        with:
          name: app-artifact
          path: ./build/libs/
      - name: Add EC2 to SSH known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts
      - name: List current directory for debugging
        run: ls -al
      - name: Copy files to EC2
        env:
          PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          HOST: ${{ secrets.EC2_HOST }}
          USER: ec2-user
        run: |
          echo "$PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem
          scp -i private_key.pem -r ./build/libs/* $USER@$HOST:/home/ec2-user/myapp/
          scp -i private_key.pem Dockerfile $USER@$HOST:/home/ec2-user/myapp/
      - name: Build and Run Docker on EC2
        run: |
          ssh -i private_key.pem $USER@$HOST << EOF
          cd /home/ec2-user/myapp
          docker build -t scrum-planner-venus .
          docker run -d -p 8080:8080 scrum-planner-venus
          EOF
